# Generated by Django 3.2 on 2022-02-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_tag', models.CharField(max_length=32)),
                ('url_path', models.CharField(max_length=256)),
                ('user_defined_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_known_ip', models.CharField(max_length=15)),
                ('user_defined_name', models.CharField(max_length=32)),
                ('color_tag', models.CharField(max_length=32)),
                ('hostname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TCPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('uid_got', models.CharField(max_length=64)),
                ('status', models.IntegerField()),
                ('time_local', models.CharField(max_length=64)),
                ('user_agent', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=15)),
                ('remote_user', models.CharField(max_length=64)),
                ('http_reference', models.CharField(max_length=64)),
                ('request', models.CharField(max_length=64)),
                ('body_bytes_sent', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDefinedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_message', models.CharField(max_length=256)),
                ('failed_code', models.IntegerField(default=500)),
                ('success_message', models.CharField(max_length=256)),
                ('success_code', models.IntegerField(default=200)),
                ('route_path', models.CharField(max_length=256)),
                ('method', models.CharField(max_length=6)),
                ('user_defined_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(max_length=15)),
                ('dest_ip', models.CharField(max_length=15)),
                ('src_mac', models.CharField(max_length=17)),
                ('dst_mac', models.CharField(max_length=17)),
                ('protocol', models.CharField(max_length=5)),
                ('ttl', models.BigIntegerField()),
                ('time_local', models.CharField(max_length=64)),
                ('time_received', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClientAPI.server')),
            ],
        ),
    ]
