# Generated by Django 3.2 on 2022-02-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdefinedlog',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClientAPI.application'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='user_defined_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
