# Generated by Django 3.2 on 2022-02-18 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAPI', '0002_auto_20220218_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlog',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClientAPI.server'),
        ),
    ]
