# Generated by Django 3.2 on 2022-02-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientAPI', '0003_alter_serverlog_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcplog',
            name='request',
            field=models.CharField(max_length=128),
        ),
    ]
